site_name: Python Steam Tradeoffer Manager
site_url: https://somespecialone.github.io/python-steam-tradeoffer-manager/

repo_name: somespecialone/python-steam-tradeoffer-manager
repo_url: https://github.com/somespecialone/python-steam-tradeoffer-manager/

copyright: Copyright &copy; 2022 <a href="https://github.com/somespecialone" target="_blank" rel="noopener">Dmitriy Tkachenko</a>

theme:
  name: material
  custom_dir: docs/theme
  logo: logo.svg
  favicon: favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/somespecialone
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/tkachenkodimitriy/
    - icon: fontawesome/brands/yahoo
      link: mailto:tkachenkodmitriy@yahoo.com
    - icon: fontawesome/brands/telegram
      link: https://t.me/somespecialone

plugins:
  - search
  - git-revision-date-localized

nav:
  - Home:
      - Overview: index.md
  - Getting started:
      - Installation: getting_started/installation.md
  - Reference:
      - Manager bot: reference/manager_bot.md
